replicaCount: 2
image:
  repository: nginx
  tag: "1.21"
service:
  type: ClusterIP
  port: 80
ingress:
  enabled: false
  hosts:
  - host: my-app.local
    paths:
    - path: /
      pathType: Prefix
