apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helloapi
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sunwukong96/assignment.git
    targetRevision: main # Replace with your branch or tag
    path: kustomize/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: dev # Replace with your desired namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

