apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloapi
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: helloapi
        image: docker.io/scarifcitadel/helloapi:v0.2.0  # Updated image
